name: built_rx_bloc_test
description: Test library for built_rx_bloc
version: 0.0.1
repository: https://github.com/AmiK2001/built_rx_bloc_test

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_value: ^8.1.3
  test: ^1.17.12
  tuple: ^2.0.0
  built_rx_bloc: ^0.0.3
  rxdart: ^0.27.3
  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  built_value_generator: ^8.1.3